In [2]:
import yfinance as yf
import numpy as np

/usr/local/lib/python3.10/dist-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()


In [3]:
#top 5 stocks
top_stocks=['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'HINDUNILVR.NS']
#download data (1yr)
data=yf.download(top_stocks,start="2023-01-01",end="2024-01-01")['Adj Close']
#Calculating returns and pct change
returns= data.pct_change().dropna()

[*********************100%%**********************]  5 of 5 completed


In [4]:
#Calculate mean returns and standard deviations of each stock
mean_returns=returns.mean()
std_dev=returns.std()

In [5]:
#Calculate covariance matrix
cov_matrix=returns.cov()

In [6]:
#Generate random portfolios
num_portfolios=1000
portfolio_weights=np.random.dirichlet(np.ones(len(top_stocks)),size=num_portfolios)

In [7]:
#Calculate portfolio returns
portfolio_returns = np.dot(portfolio_weights, mean_returns)

In [9]:
#Calculate portfolio std dev using the averaging out method
portfolio_std_dev = np.sqrt(np.dot(portfolio_weights*2, std_dev*2) +
                             np.dot(np.dot(portfolio_weights, cov_matrix), portfolio_weights.T))
print("Portfolio Standard Deviation:",portfolio_std_dev)

Portfolio Standard Deviation: [[0.20582165 0.21890422 0.21910955 ... 0.21761837 0.21374484 0.22037132]
 [0.20581536 0.2189555  0.21916954 ... 0.21767589 0.2137734  0.2204192 ]
 [0.20580928 0.21895855 0.21918114 ... 0.21767713 0.21375814 0.22041211]
 ...
 [0.2058058  0.21895242 0.21916465 ... 0.217687   0.21377179 0.22041785]
 [0.20582216 0.2189385  0.21913462 ... 0.2176603  0.21381375 0.22042589]
 [0.20582282 0.21895944 0.2191633  ... 0.21768159 0.21380175 0.22043696]]


In [11]:
#Calculate the expected shortfall of the portfolio
alpha=0.05#Confidence level
portfolio_sorted_returns= np.sort(portfolio_returns)
VaR = portfolio_sorted_returns[int(num_portfolios*alpha)]
expected_shortfall=portfolio_sorted_returns[:int(num_portfolios*alpha)].mean()
print("Value at Risk(VaR):",VaR)
print("Portfolio Expected Shortfall at {}% confidence level: {:.6f}".format((1-alpha)*100, expected_shortfall))

Value at Risk(VaR): 0.00032476982828905717
Portfolio Expected Shortfall at 95.0% confidence level: 0.000314
